<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NatCom [	<!ELEMENT NationalCommission (Country, Name, Address, NCHeads)>	<!ELEMENT NCHeads (NCHead)*>	<!ELEMENT NCHead (CountryCode, NameDel, TitleDel, Photo)>	<!ELEMENT Country (#PCDATA)>	<!ELEMENT Name (#PCDATA)>	<!ELEMENT Address (#PCDATA)>	<!ELEMENT Phone (#PCDATA)>	<!ELEMENT Fax (#PCDATA)>	<!ELEMENT Email (#PCDATA)>	<!ELEMENT WebsiteNC (#PCDATA)>	<!ELEMENT WebsiteUNESCO (#PCDATA)>	<!ELEMENT CountryCode (#PCDATA)>	<!ELEMENT NameDel (#PCDATA)>	<!ELEMENT TitleDel (#PCDATA)>	<!ELEMENT Photo (#PCDATA)>	<!ATTLIST NationalCommission countryid CDATA #REQUIRED>	<!ATTLIST Country xml:lang (zz|en|fr) "en" >	<!ATTLIST Name xml:lang (en|fr) "en" >	<!ATTLIST WebsiteUNESCO xml:lang (en|fr|es) "en" >]>
<NatCom><NationalCommission countryid="AF"><Country xml:lang="en">Afghanistan</Country><Country xml:lang="fr">Afghanistan</Country><Name xml:lang="zz">Afghan National Commission for UNESCO</Name><Name xml:lang="en">Afghan National Commission for UNESCO</Name><Name xml:lang="fr">Commission nationale afghane pour l'UNESCO</Name><Address><![CDATA[Permanent Delegation of Afghanistan to UNESCO 
Maison de l'UNESCO 
Bureau MS1.48/49/50 
1, rue Miollis 
75732 PARIS CEDEX 15 

]]></Address><Phone><![CDATA[]]></Phone><Fax><![CDATA[+93202103848]]></Fax><Email><![CDATA[unesco.natcom@moe.gov.af; dl.afghanistan@unesco-delegations.org ]]></Email><WebsiteNC><![CDATA[]]></WebsiteNC><WebsiteUNESCO xml:lang="en"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=AF&language=E]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="fr"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=AF&language=F]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="es"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=AF&language=S]]></WebsiteUNESCO><NCHeads><NCHead memberid="1345"><CountryCode>AF</CountryCode><NameDel xml:lang="en">H.E. Mr Ghulam Farooq Wardak *</NameDel><TitleDel xml:lang="en"><![CDATA[Chairman]]></TitleDel><Photo>http://www.unesco.org/ncp/images/ncdir_1345.jpg</Photo></NCHead><NCHead memberid="1957"><CountryCode>AF</CountryCode><NameDel xml:lang="en">Mr Mohammad Usman Kamran</NameDel><TitleDel xml:lang="en"><![CDATA[Acting Secretary-General]]></TitleDel></NCHead></NCHeads></NationalCommission><NationalCommission countryid="AI"><Country xml:lang="en">Anguilla</Country><Country xml:lang="fr">Anguilla</Country><Name xml:lang="zz">Ministry of Finance, Economic Development Investment Commerce and Tourism</Name><Name xml:lang="en"/><Name xml:lang="fr"/><Address><![CDATA[PO Box 60 ,
The Secretariat ,
The Valley ,
Anguilla
 BWI
]]></Address><Phone><![CDATA[]]></Phone><Fax><![CDATA[]]></Fax><Email><![CDATA[jasmingarraway@yahoo.com]]></Email><WebsiteNC><![CDATA[]]></WebsiteNC><WebsiteUNESCO xml:lang="en"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=AI&language=E]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="fr"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=AI&language=F]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="es"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=AI&language=S]]></WebsiteUNESCO></NationalCommission><NationalCommission countryid="AL"><Country xml:lang="en">Albania</Country><Country xml:lang="fr">Albanie</Country><Name xml:lang="zz">Commission nationale albanaise pour l' UNESCO</Name><Name xml:lang="en">Albanian National Commission for UNESCO</Name><Name xml:lang="fr">Commission nationale albanaise pour l'UNESCO</Name><Address><![CDATA[Ministria e Puneve të Jashtme
Zyra e UNESCO
Bulevard Zhan d'Ark
Tirana
Albania]]></Address><Phone><![CDATA[+355 4 23 64 090 
+355 4 23 64 060  ext. 79 202 (SG) 
]]></Phone><Fax><![CDATA[+355 4 23 62 084; +355 4 23 62 085 
]]></Fax><Email><![CDATA[unesco.al@mfa.gov.al]]></Email><WebsiteNC><![CDATA[http://www.unesco.al]]></WebsiteNC><WebsiteUNESCO xml:lang="en"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=AL&language=E]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="fr"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=AL&language=F]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="es"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=AL&language=S]]></WebsiteUNESCO><NCHeads><NCHead memberid="1918"><CountryCode>AL</CountryCode><NameDel xml:lang="en">Ms Lindita Nikolla</NameDel><TitleDel xml:lang="en"><![CDATA[President]]></TitleDel></NCHead><NCHead memberid="2005"><CountryCode>AL</CountryCode><NameDel xml:lang="en">Mr Virgjil Muçi</NameDel><TitleDel xml:lang="en"><![CDATA[Secretary-General]]></TitleDel></NCHead></NCHeads></NationalCommission><NationalCommission countryid="DZ"><Country xml:lang="en">Algeria</Country><Country xml:lang="fr">Algérie</Country><Name xml:lang="zz">Commission nationale algérienne pour l'éducation, la science et la culture</Name><Name xml:lang="en"/><Name xml:lang="fr">Commission nationale algérienne pour l'éducation, la science et la culture</Name><Address><![CDATA[Palais Mustapha Bacha
06 Avenue de l'indépendance
16000 ALGER
Algérie]]></Address><Phone><![CDATA[(213-21) 66 86 24]]></Phone><Fax><![CDATA[(213-21) 66 82 83]]></Fax><Email><![CDATA[unesco.algerie@live.fr; natcomalgerie@unesco.dz]]></Email><WebsiteNC><![CDATA[www.unesco.dz ]]></WebsiteNC><WebsiteUNESCO xml:lang="en"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=DZ&language=E]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="fr"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=DZ&language=F]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="es"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=DZ&language=S]]></WebsiteUNESCO><NCHeads><NCHead memberid="2043"><CountryCode>DZ</CountryCode><NameDel xml:lang="en">S.Exc. Madame Nouria BENGHEBRIT</NameDel><TitleDel xml:lang="en"><![CDATA[Présidente]]></TitleDel></NCHead><NCHead memberid="1884"><CountryCode>DZ</CountryCode><NameDel xml:lang="en">Mme Dalila NEDJRAOUI</NameDel><TitleDel xml:lang="en"><![CDATA[Sécretaire générale]]></TitleDel></NCHead></NCHeads></NationalCommission><NationalCommission countryid="AD"><Country xml:lang="en">Andorra</Country><Country xml:lang="fr">Andorre</Country><Name xml:lang="zz">Comissió Nacional Andorrana per a la UNESCO</Name><Name xml:lang="en">Andorran National Commission for UNESCO</Name><Name xml:lang="fr">Commission Nationale Andorrane pour l'UNESCO</Name><Address><![CDATA[C/ Prat de la Creu, 68-76 PB
AD500 Andorra la Vella
Principauté d'Andorre]]></Address><Phone><![CDATA[(+376) 825 700 (direct);
]]></Phone><Fax><![CDATA[(+376) 861 911 (direct);
]]></Fax><Email><![CDATA[cnau.unesco@andorra.ad; jmarmengol@andorra.ad; ]]></Email><WebsiteNC><![CDATA[http://www.unesco.ad ]]></WebsiteNC><WebsiteUNESCO xml:lang="en"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=AD&language=E]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="fr"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=AD&language=F]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="es"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=AD&language=S]]></WebsiteUNESCO><NCHeads><NCHead memberid="1784"><CountryCode>AD</CountryCode><NameDel xml:lang="en">Mme. Elisenda Vives</NameDel><TitleDel xml:lang="en"><![CDATA[Présidente]]></TitleDel><Photo>http://www.unesco.org/ncp/images/ncdir_1784.jpg</Photo></NCHead><NCHead memberid="466"><CountryCode>AD</CountryCode><NameDel xml:lang="en">M. Jean-Michel Armengol</NameDel><TitleDel xml:lang="en"><![CDATA[Secrétaire général]]></TitleDel></NCHead></NCHeads></NationalCommission><NationalCommission countryid="AO"><Country xml:lang="en">Angola</Country><Country xml:lang="fr">Angola</Country><Name xml:lang="zz">Commission nationale angolaise pour l'UNESCO</Name><Name xml:lang="en">Angola National Commission for UNESCO</Name><Name xml:lang="fr">Commission nationale angolaise pour l'UNESCO</Name><Address><![CDATA[C.P. 1451
LUANDA
Angola]]></Address><Phone><![CDATA[(244.222) 33 70 10;
(244.222) 33 70 13;
(244.91) 25 04 714 (portable SG)]]></Phone><Fax><![CDATA[(244.222) 39.21.38 (Com.nat.)]]></Fax><Email><![CDATA[unesco2@snet.co.ao; mtquarta@gmail.com (SG)]]></Email><WebsiteNC><![CDATA[]]></WebsiteNC><WebsiteUNESCO xml:lang="en"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=AO&language=E]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="fr"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=AO&language=F]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="es"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=AO&language=S]]></WebsiteUNESCO><NCHeads><NCHead memberid="1582"><CountryCode>AO</CountryCode><NameDel xml:lang="en">M. M’pinda Simao*</NameDel><TitleDel xml:lang="en"><![CDATA[Président]]></TitleDel></NCHead><NCHead memberid="185"><CountryCode>AO</CountryCode><NameDel xml:lang="en">M. Manuel Teodoro Quarta</NameDel><TitleDel xml:lang="en"><![CDATA[Secrétaire permanent]]></TitleDel></NCHead></NCHeads></NationalCommission><NationalCommission countryid="AG"><Country xml:lang="en">Antigua and Barbuda</Country><Country xml:lang="fr">Antigua-et-Barbuda</Country><Name xml:lang="zz">Antigua and Barbuda National Commission for UNESCO</Name><Name xml:lang="en">Antigua and Barbuda National Commission for UNESCO</Name><Name xml:lang="fr">Commission nationale Antigua et Barbuda pour l'UNESCO</Name><Address><![CDATA[Ministry of Education, Culture, and Technology
Church Street
St. John's
Antigua W.I.
Antigua and Barbuda]]></Address><Phone><![CDATA[(1-268) 462.4959]]></Phone><Fax><![CDATA[(1-268) 462.4970]]></Fax><Email><![CDATA[regmurphy@hotmail.com (SG); unescoantiguabarbuda@gmail.com]]></Email><WebsiteNC><![CDATA[]]></WebsiteNC><WebsiteUNESCO xml:lang="en"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=AG&language=E]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="fr"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=AG&language=F]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="es"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=AG&language=S]]></WebsiteUNESCO><NCHeads><NCHead memberid="1392"><CountryCode>AG</CountryCode><NameDel xml:lang="en">Dr. The Hon. Jacqui Quinn Leandro *</NameDel><TitleDel xml:lang="en"><![CDATA[Chair]]></TitleDel><Photo>http://www.unesco.org/ncp/images/ncdir_1392.jpg</Photo></NCHead><NCHead memberid="1317"><CountryCode>AG</CountryCode><NameDel xml:lang="en">Dr. Reginald Murphy</NameDel><TitleDel xml:lang="en"><![CDATA[Secretary-General]]></TitleDel></NCHead></NCHeads></NationalCommission><NationalCommission countryid="AR"><Country xml:lang="en">Argentina</Country><Country xml:lang="fr">Argentine</Country><Name xml:lang="zz">Comisión Nacional Argentina de Cooperación con la UNESCO</Name><Name xml:lang="en">Argentina National Commission for Cooperation with UNESCO</Name><Name xml:lang="fr"/><Address><![CDATA[Pizzurno 935
P.B. Of. 20
1020 BUENOS AIRES 
República Argentina]]></Address><Phone><![CDATA[(54.11) 41 29 11 56
(54) 11 4129-1152 (SG)
(54) 11 6209-1934 (SG movil)]]></Phone><Fax><![CDATA[(54 11) 41 29 11 57; (54 11) 41 29 12 85]]></Fax><Email><![CDATA[conaplu@me.gov.ar; burtonjuliana@gmail.com (SG)]]></Email><WebsiteNC><![CDATA[]]></WebsiteNC><WebsiteUNESCO xml:lang="en"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=AR&language=E]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="fr"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=AR&language=F]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="es"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=AR&language=S]]></WebsiteUNESCO><NCHeads><NCHead memberid="1440"><CountryCode>AR</CountryCode><NameDel xml:lang="en">Sr Alberto Estanislao Sileoni *</NameDel><TitleDel xml:lang="en"><![CDATA[Presidente]]></TitleDel><Photo>http://www.unesco.org/ncp/images/ncdir_1440.gif</Photo></NCHead><NCHead memberid="1898"><CountryCode>AR</CountryCode><NameDel xml:lang="en">Lic Juliana BURTON</NameDel><TitleDel xml:lang="en"><![CDATA[Secretaria Ejecutiva]]></TitleDel><Photo>http://www.unesco.org/ncp/images/ncdir_1898.jpg</Photo></NCHead></NCHeads></NationalCommission><NationalCommission countryid="AM"><Country xml:lang="en">Armenia</Country><Country xml:lang="fr">Arménie</Country><Name xml:lang="zz">Armenian National Commission for UNESCO</Name><Name xml:lang="en">Armenian National Commission for UNESCO</Name><Name xml:lang="fr">Commission nationale arménienne pour l'UNESCO</Name><Address><![CDATA[Ministry of Foreign Affairs  
2, Government House
Republic Square
0010 Yerevan
Armenia]]></Address><Phone><![CDATA[(374-10) 54-40-41 (Ext. 212)]]></Phone><Fax><![CDATA[(374-10) 54-39-25]]></Fax><Email><![CDATA[v.kazhoyan@mfa.am (SG); k.mehrabekyan@mfa.am]]></Email><WebsiteNC><![CDATA[http://www.unesco.am]]></WebsiteNC><WebsiteUNESCO xml:lang="en"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=AM&language=E]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="fr"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=AM&language=F]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="es"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=AM&language=S]]></WebsiteUNESCO><NCHeads><NCHead memberid="1297"><CountryCode>AM</CountryCode><NameDel xml:lang="en">Mr. Edward Nalbandyan *</NameDel><TitleDel xml:lang="en"><![CDATA[President]]></TitleDel><Photo>http://www.unesco.org/ncp/images/ncdir_1297.jpg</Photo></NCHead><NCHead memberid="1548"><CountryCode>AM</CountryCode><NameDel xml:lang="en">Mr Vahram Kazhoyan</NameDel><TitleDel xml:lang="en"><![CDATA[Secretary-General]]></TitleDel></NCHead></NCHeads></NationalCommission><NationalCommission countryid="AW"><Country xml:lang="en">Aruba</Country><Country xml:lang="fr">Aruba</Country><Name xml:lang="zz">Aruba National Commission for UNESCO</Name><Name xml:lang="en">Aruba National Commission for UNESCO</Name><Name xml:lang="fr"/><Address><![CDATA[L.G. Smith Blvd 22 
Oranjestad
Aruba 

]]></Address><Phone><![CDATA[(297) 583-5863]]></Phone><Fax><![CDATA[(297) 583-5009]]></Fax><Email><![CDATA[unescoaruba@gmail.com;]]></Email><WebsiteNC><![CDATA[http://www.unesco-aruba.org]]></WebsiteNC><WebsiteUNESCO xml:lang="en"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=AW&language=E]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="fr"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=AW&language=F]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="es"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=AW&language=S]]></WebsiteUNESCO><NCHeads><NCHead memberid="485"><CountryCode>AW</CountryCode><NameDel xml:lang="en">Mr James A. Oduber</NameDel><TitleDel xml:lang="en"><![CDATA[Secretary-General]]></TitleDel></NCHead></NCHeads></NationalCommission><NationalCommission countryid="AU"><Country xml:lang="en">Australia</Country><Country xml:lang="fr">Australie</Country><Name xml:lang="zz">Australian National Commission for UNESCO</Name><Name xml:lang="en">Australian National Commission for UNESCO</Name><Name xml:lang="fr">Commission nationale australienne pour l'UNESCO</Name><Address><![CDATA[International Organizations Branch
Department of Foreign Affairs and Trade
R.G. Casey Building
John McEwen Crescent
Barton ACT 0221
Australia]]></Address><Phone><![CDATA[(61.2) 6261 2037]]></Phone><Fax><![CDATA[(61.2) 6112 3138 (SG)
(61.2) 6112 2037 (PT)

]]></Fax><Email><![CDATA[natcom.unesco@dfat.gov.au]]></Email><WebsiteNC><![CDATA[http://www.dfat.gov.au/intorgs/unesco]]></WebsiteNC><WebsiteUNESCO xml:lang="en"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=AU&language=E]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="fr"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=AU&language=F]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="es"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=AU&language=S]]></WebsiteUNESCO><NCHeads><NCHead memberid="1907"><CountryCode>AU</CountryCode><NameDel xml:lang="en">Ms Annmaree O’Keeffe AM</NameDel><TitleDel xml:lang="en"><![CDATA[Chairperson]]></TitleDel><Photo>http://www.unesco.org/ncp/images/ncdir_1907.jpg</Photo></NCHead><NCHead memberid="2008"><CountryCode>AU</CountryCode><NameDel xml:lang="en">Mr Dario Morosini</NameDel><TitleDel xml:lang="en"><![CDATA[Secretary-General]]></TitleDel></NCHead></NCHeads></NationalCommission><NationalCommission countryid="AT"><Country xml:lang="en">Austria</Country><Country xml:lang="fr">Autriche</Country><Name xml:lang="zz">Austrian Commission for UNESCO</Name><Name xml:lang="en">Austrian Commission for UNESCO</Name><Name xml:lang="fr">Commission  autrichienne pour l'UNESCO</Name><Address><![CDATA[Universitätsstraße 5/4. Floor/12
A-1010 Vienna
Austria]]></Address><Phone><![CDATA[(43-1) 526 13 01]]></Phone><Fax><![CDATA[(43-1) 526 13 01 - 20]]></Fax><Email><![CDATA[oeuk@unesco.at, eschig@unesco.at (SG)]]></Email><WebsiteNC><![CDATA[http://www.unesco.at]]></WebsiteNC><WebsiteUNESCO xml:lang="en"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=AT&language=E]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="fr"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=AT&language=F]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="es"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=AT&language=S]]></WebsiteUNESCO><NCHeads><NCHead memberid="1272"><CountryCode>AT</CountryCode><NameDel xml:lang="en">Dr. Eva Nowotny</NameDel><TitleDel xml:lang="en"><![CDATA[President]]></TitleDel><Photo>http://www.unesco.org/ncp/images/ncdir_1272.jpg</Photo></NCHead><NCHead memberid="1176"><CountryCode>AT</CountryCode><NameDel xml:lang="en">Ms Gabriele Eschig</NameDel><TitleDel xml:lang="en"><![CDATA[Secretary-General]]></TitleDel><Photo>http://www.unesco.org/ncp/images/ncdir_1176.jpg</Photo></NCHead></NCHeads></NationalCommission><NationalCommission countryid="AZ"><Country xml:lang="en">Azerbaijan</Country><Country xml:lang="fr">Azerbaïdjan</Country><Name xml:lang="zz">National Commission of the Republic of Azerbaijan for UNESCO</Name><Name xml:lang="en">National Commission of the Republic of Azerbaijan for UNESCO</Name><Name xml:lang="fr">Commission nationale de la République d'Azerbaijan pour l'UNESCO</Name><Address><![CDATA[Ministry of Foreign Affairs
Shikhali Gurbanov Str. 4
1009 Baku
Azerbaijan]]></Address><Phone><![CDATA[(994.12) 596 93 22;
(994.12) 596 90 72;
]]></Phone><Fax><![CDATA[(994.12)  596 94 07]]></Fax><Email><![CDATA[unesco@mfa.gov.az;]]></Email><WebsiteNC><![CDATA[]]></WebsiteNC><WebsiteUNESCO xml:lang="en"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=AZ&language=E]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="fr"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=AZ&language=F]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="es"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=AZ&language=S]]></WebsiteUNESCO><NCHeads><NCHead memberid="21"><CountryCode>AZ</CountryCode><NameDel xml:lang="en"> M. Elmar Mammadyarov*</NameDel><TitleDel xml:lang="en"><![CDATA[Chairperson]]></TitleDel></NCHead><NCHead memberid="1406"><CountryCode>AZ</CountryCode><NameDel xml:lang="en">Mrs Gunay Efendiyeva</NameDel><TitleDel xml:lang="en"><![CDATA[Secretary-General]]></TitleDel></NCHead></NCHeads></NationalCommission><NationalCommission countryid="BH"><Country xml:lang="en">Bahrain</Country><Country xml:lang="fr">Bahreïn</Country><Name xml:lang="zz">Bahrain National Commission for UNESCO</Name><Name xml:lang="en">Bahrain National Commission for UNESCO</Name><Name xml:lang="fr">Commission nationale de Bahrain pour l'UNESCO</Name><Address><![CDATA[Ministry of Education
Manama
Bahrain]]></Address><Phone><![CDATA[(00973)  17783091-17783118
]]></Phone><Fax><![CDATA[(973) 17 68 11 04
]]></Fax><Email><![CDATA[bahrainnatcom@moe.gov.bh; kefayaalanzoor@gmail.com]]></Email><WebsiteNC><![CDATA[http://www.education.gov.bh (Mineduc)]]></WebsiteNC><WebsiteUNESCO xml:lang="en"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=BH&language=E]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="fr"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=BH&language=F]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="es"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=BH&language=S]]></WebsiteUNESCO><NCHeads><NCHead memberid="32"><CountryCode>BH</CountryCode><NameDel xml:lang="en">Dr Majed  Ali Al Noaimi *</NameDel><TitleDel xml:lang="en"><![CDATA[Chairperson]]></TitleDel></NCHead><NCHead memberid="1380"><CountryCode>BH</CountryCode><NameDel xml:lang="en">Mr Ghazi Isa Almarzooq</NameDel><TitleDel xml:lang="en"><![CDATA[Secretary-General]]></TitleDel></NCHead></NCHeads></NationalCommission><NationalCommission countryid="BB"><Country xml:lang="en">Barbados</Country><Country xml:lang="fr">Barbade</Country><Name xml:lang="zz">Barbados National Commission for UNESCO</Name><Name xml:lang="en">Barbados National Commission for UNESCO</Name><Name xml:lang="fr">Commission nationale des Barbades pour l'UNESCO</Name><Address><![CDATA[Ministry of Education, Science, Technology and Innovation
The Elsie Payne Complex
Constitution Road
St Michael
Barbados]]></Address><Phone><![CDATA[(1.246) 430 27 02 (Sec-Gen); (1.246) 430 27 89 (Gen-Office)]]></Phone><Fax><![CDATA[(1.246) 436 24 11 FAX]]></Fax><Email><![CDATA[unescobgi@mes.gov.bb;  alissandra.cummins@gmail.com;]]></Email><WebsiteNC><![CDATA[http://mes.gov.bb]]></WebsiteNC><WebsiteUNESCO xml:lang="en"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=BB&language=E]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="fr"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=BB&language=F]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="es"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=BB&language=S]]></WebsiteUNESCO><NCHeads><NCHead memberid="60"><CountryCode>BB</CountryCode><NameDel xml:lang="en">Ms Allisandra Cummins</NameDel><TitleDel xml:lang="en"><![CDATA[Chairperson]]></TitleDel></NCHead><NCHead memberid="61"><CountryCode>BB</CountryCode><NameDel xml:lang="en">Mr. Laurie King</NameDel><TitleDel xml:lang="en"><![CDATA[Deputy Chairperson]]></TitleDel></NCHead><NCHead memberid="1646"><CountryCode>BB</CountryCode><NameDel xml:lang="en">Ms Juliette Griffith</NameDel><TitleDel xml:lang="en"><![CDATA[Secretary General]]></TitleDel></NCHead></NCHeads></NationalCommission><NationalCommission countryid="BI"><Country xml:lang="en">Burundi</Country><Country xml:lang="fr">Burundi</Country><Name xml:lang="zz">Commission nationale du Burundi pour l'UNESCO</Name><Name xml:lang="en"/><Name xml:lang="fr">Commission nationale du Burundi pour l'UNESCO</Name><Address><![CDATA[Ministère de l'Education nationale
Boulevard de l'Uprona
B.P. 1990
BUJUMBURA
Burundi]]></Address><Phone><![CDATA[(257) 22 22 4517 (Secrétariat du Sec. perm.);
(257) 22 22 45 247(Secrétariat du Président);
(257) 22 22 37 55 (SG)
(257) 77 77 14 69 (SG portable)
(257) 71 30 00 02 (SG portable)
(257) 22 25 33 53 (Dir. Minéduc)]]></Phone><Fax><![CDATA[(257)  22 223755  (Sec. Permanent) ;
(257) 22 228477 (Minéduc)]]></Fax><Email><![CDATA[abarutwa@yahoo.fr; salvatornyabenda@ymail.com (SG)]]></Email><WebsiteNC><![CDATA[]]></WebsiteNC><WebsiteUNESCO xml:lang="en"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=BI&language=E]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="fr"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=BI&language=F]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="es"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=BI&language=S]]></WebsiteUNESCO><NCHeads><NCHead memberid="1857"><CountryCode>BI</CountryCode><NameDel xml:lang="en">Dr Joseph BUTORE*</NameDel><TitleDel xml:lang="en"><![CDATA[Président]]></TitleDel></NCHead><NCHead memberid="1759"><CountryCode>BI</CountryCode><NameDel xml:lang="en">M Salvator Nyabenda</NameDel><TitleDel xml:lang="en"><![CDATA[Secrétaire permanent]]></TitleDel></NCHead></NCHeads></NationalCommission><NationalCommission countryid="BE"><Country xml:lang="en">Belgium</Country><Country xml:lang="fr">Belgique</Country><Name xml:lang="zz">Commissions belges pour l'UNESCO</Name><Name xml:lang="en">Flemish Commission for UNESCO - Belgian French speaking and German speaking Commission for UNESCO</Name><Name xml:lang="fr">Commission flamande pour l'UNESCO - Commission belge francophone et germanophone pour l'UNESCO</Name><Address><![CDATA[Secretariat of the Flemish Commission for UNESCO
Foreign Affairs Division
Boudewijnlaan 30 bus 80
1000 Brussels
Belgium  

Sécretariat de la Commission belge francophone et germanophone pour l’UNESCO
Place Sainctelette, 2
1080 Bruxelles 
Belgique

]]></Address><Phone><![CDATA[- Commission flamande pour l’UNESCO:  +32 (0)25 53 50 11(SG)
- Commission  belge francophone et germanophone pour l’UNESCO: + 32(0)2 421 85 70 (SG)]]></Phone><Fax><![CDATA[Commission flamande pour l’UNESCO: +32 (0)2 553 60 37 (SG)
Commission belge francophone et germanophone pour l'UNESCO +32-2-421.87.69]]></Fax><Email><![CDATA[Commission flamande pour l’UNESCO: marc.vervenne@gbeg.kuleuven.be (Pt); tijs.dhoest@iv.vlaanderen.be (SG); Commission belge francophone et germanophone pour l’UNESCO: m.faure@wbi.be (SG); Secrétariat de la Commission nationale belge pour l'UNESCO: dl.belgium@unesco-delegations.org, Pour toutes les informations par courriel:  multilateraal@vlaanderen.be]]></Email><WebsiteNC><![CDATA[]]></WebsiteNC><WebsiteUNESCO xml:lang="en"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=BE&language=E]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="fr"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=BE&language=F]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="es"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=BE&language=S]]></WebsiteUNESCO><NCHeads><NCHead memberid="1539"><CountryCode>BE</CountryCode><NameDel xml:lang="en">Prof. Marc Vervenne</NameDel><TitleDel xml:lang="en"><![CDATA[Président de la Commission flamande pour l’UNESCO]]></TitleDel></NCHead><NCHead memberid="1132"><CountryCode>BE</CountryCode><NameDel xml:lang="en">M. Philippe Busquin</NameDel><TitleDel xml:lang="en"><![CDATA[Président de la Commission belge francophone et germanophone pour l’UNESCO]]></TitleDel></NCHead><NCHead memberid="1126"><CountryCode>BE</CountryCode><NameDel xml:lang="en">M. Marien Faure</NameDel><TitleDel xml:lang="en"><![CDATA[Secrétaire général de la Commission belge francophone et germanophone pour l’UNESCO]]></TitleDel></NCHead><NCHead memberid="1751"><CountryCode>BE</CountryCode><NameDel xml:lang="en">Mr Tijs D’Hoest</NameDel><TitleDel xml:lang="en"><![CDATA[Secretary-General of the Flemish Commission for UNESCO]]></TitleDel></NCHead></NCHeads></NationalCommission><NationalCommission countryid="BJ"><Country xml:lang="en">Benin</Country><Country xml:lang="fr">Bénin</Country><Name xml:lang="zz">Commission nationale béninoise pour l'UNESCO (CNBU)</Name><Name xml:lang="en">National Commission of Benin for UNESCO</Name><Name xml:lang="fr">Commission nationale béninoise pour l'UNESCO (CNBU)</Name><Address><![CDATA[Boulevard Lagunaire
PORTO-NOVO]]></Address><Phone><![CDATA[(229) 20 22 00 66;
(229) 20 22 00 65 (SG, Tel./fax)
(229)  97 35 22 53 (SG portable)]]></Phone><Fax><![CDATA[(229) 20 22 00 65 (SG, Tel./fax)]]></Fax><Email><![CDATA[spcnbu@yahoo.fr; marcelndah@yahoo.fr (SG)]]></Email><WebsiteNC><![CDATA[]]></WebsiteNC><WebsiteUNESCO xml:lang="en"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=BJ&language=E]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="fr"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=BJ&language=F]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="es"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=BJ&language=S]]></WebsiteUNESCO><NCHeads><NCHead memberid="1413"><CountryCode>BJ</CountryCode><NameDel xml:lang="en">M. Félicien Zackarie *</NameDel><TitleDel xml:lang="en"><![CDATA[Président]]></TitleDel><Photo>http://www.unesco.org/ncp/images/ncdir_1413.jpg</Photo></NCHead><NCHead memberid="1762"><CountryCode>BJ</CountryCode><NameDel xml:lang="en">M N’dah Marcel OYA</NameDel><TitleDel xml:lang="en"><![CDATA[Secrétaire générale]]></TitleDel><Photo>http://www.unesco.org/ncp/images/ncdir_1762.jpg</Photo></NCHead></NCHeads></NationalCommission><NationalCommission countryid="BD"><Country xml:lang="en">Bangladesh</Country><Country xml:lang="fr">Bangladesh</Country><Name xml:lang="zz">Bangladesh National Commission for UNESCO</Name><Name xml:lang="en">Bangladesh National Commission for UNESCO</Name><Name xml:lang="fr">Commission nationale du Bangladesh pour l'UNESCO</Name><Address><![CDATA[Ministry of Education
1, Asian Highway
Palassy-Nilkhet
Dhaka-1205
Bangladesh]]></Address><Phone><![CDATA[(88 02) 716 13 95 (Chairman); (88 02) 9576679(SG);
 
]]></Phone><Fax><![CDATA[+880 2 9514114/8613420/9662007]]></Fax><Email><![CDATA[secretary@moedu.gov.bd; info@moedu.gov.bd; natcombd@yahoo.com;  monjur_1967@yahoo.com]]></Email><WebsiteNC><![CDATA[http://www.bncu.gov.bd]]></WebsiteNC><WebsiteUNESCO xml:lang="en"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=BD&language=E]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="fr"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=BD&language=F]]></WebsiteUNESCO><WebsiteUNESCO xml:lang="es"><![CDATA[http://www.unesco.org/nac/geoportal.php?country=BD&language=S]]></WebsiteUNESCO><NCHeads><NCHead memberid="1387"><CountryCode>BD</CountryCode><NameDel xml:lang="en">H.E. Mr Nurul Islam Nahid *</NameDel><TitleDel xml:lang="en"><![CDATA[Chairman]]></TitleDel></NCHead><NCHead memberid="1984"><CountryCode>BD</CountryCode><NameDel xml:lang="en">Mr. Md. Nazrul Islam Khan</NameDel><TitleDel xml:lang="en"><![CDATA[Secretary-General]]></TitleDel></NCHead><NCHead memberid="1906"><CountryCode>BD</CountryCode><NameDel xml:lang="en">Mr Md. Monjur Hossain</NameDel><TitleDel xml:lang="en"><![CDATA[Secretary]]></TitleDel></NCHead></NCHeads></NationalCommission><NationalCommission countryid="BS"><Country xml:lang="en">Bahamas</Country><Country xml:lang="fr">Bahamas</Country><Name xml:lang="zz">Bahamas National Commission for UNESCO</Name><Name xml:lang="en">Bahamas National Commission for UNESCO</Name><Name xml:lang="fr">Commission nationale des Bahamas pour l'UNESCO</Name><Address><![CDATA[Ministry of Education
P.O. Box N-3913/14
Thompson Boulevard
Nassau
Bahamas]]></Address><Phone><![CDATA[(1.242) 502- 8215; 
(1.242) 328-6069 (SecGen's direct line) ;
(1.242) 502-8204; 